### PR TITLE
FISH-6680 Revert FISH-6696

### PR DESCRIPTION
**Pull request by arieki**
Revert "FISH-6596 duplicate javax form data with jakarta prefix"

This reverts commit cd406ac5d0f746d3e39257bd3428586471a18988.

### CODE REVIEW

**Comment by Pandrex247** [comment]
Could we not fix this rather than reverting and having to reapply it?

**Comment by arieki** [comment]
> Could we not fix this rather than reverting and having to reapply it?

I am thinking of re-apply it on p2. but yeah it makes more sense to fix it on p1. I will close this PR then

**Comment by Pandrex247** [comment]
P1 is already released.
We shouldn't be redeploying already released artefacts, even if they're broken.

**Comment by arieki** [comment]
> P1 is already released. We shouldn't be redeploying already released artefacts, even if they're broken.

Understood

**Pull request closed without merging**
